=== DanielPobarzin/WSService-DataModules/Client/Client/Communications/bin/Debug/net8.0/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "ClientId": { "type": "string" },
    "DbConnection": {
      "type": "object",
      "properties": {
        "DataBase": { "type": "string" },
        "NotifyConnectionString": { "type": "string" },
        "AlarmConnectionString": { "type": "string" }
      },
      "required": [ "DataBase", "NotifyConnectionString", "AlarmConnectionString" ]
    },
    "ClientSettings": {
      "type": "object",
      "properties": {
        "ClientId": { "type": "string" },
        "UseCache": { "type": "boolean" },
        "Mode": { "type": "string" }
      },
      "required": [ "ClientId", "Mode" ]
    },
    "ConnectionSettings": {
      "type": "object",
      "properties": {
        "AlarmUrl": {
          "type": "string",
          "format": "uri"
        },
        "NotifyUrl": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [ "AlarmUrl", "NotifyUrl" ]
    },
    "Kafka": {
      "type": "object",
      "properties": {
        "Producer": {
          "type": "object",
          "properties": {
            "BootstrapServers": {
              "type": "string",
              "format": "uri"
            }
          },
          "required": [ "BootstrapServers" ]
        },
        "Consumer": {
          "type": "object",
          "properties": {
            "BootstrapServers": {
              "type": "string",
              "format": "uri"
            }
          },
          "required": [ "BootstrapServers" ]

        }
      },
      "required": [ "Producer", "Consumer" ]
    }
  },
    "required": [ "DbConnection", "ClientSettings", "ConnectionSettings", "Kafka" ]
}

=== DanielPobarzin/WSService-DataModules/Client/Client/Communications/bin/Debug/net8.0/configure.json
{
  "ClientId": "00000000-0000-0000-0000-000000000000",
  "DbConnection": {
    "DataBase": "PostgreSQL",
    "NotifyConnectionString": "host=localhost;port=5432;Database=NotificationsExchangeClients;Username=postgres;Password=19346jaidj",
    "AlarmConnectionString": "host=localhost;port=5432;Database=AlarmsExchangeClients;Username=postgres;Password=19346jaidj"
  },
  "ClientSettings": {
    "ClientId": "11341fac-11e6-8b0c-aa4c-cfcf5346a113",
    "UseCache": true,
    "Mode": "Manual"
  },
  "ConnectionSettings": {
    "NotifyUrl": "https://localhost:8080/hubs/NotificationHub/Send",
    "AlarmUrl": "https://localhost:8080/hubs/AlarmHub/Send"
  },
  "Kafka": {
    "Producer": {
      "BootstrapServers": "localhost:9092"
    },
    "Consumer": {
      "BootstrapServers": "localhost:9092"
    }
  }
}

=== DanielPobarzin/WSService-DataModules/Client/Client/Communications/bin/Debug/net8.0/configureDefault.json
{
  "DbConnection": {
    "DataBase": "PostgreSQL",
    "NotifyConnectionString": "host=localhost;port=5432;Database=NotificationsExchangeClients;Username=postgres;Password=19346jaidj",
    "AlarmConnectionString": "host=localhost;port=5432;Database=AlarmsExchangeClients;Username=postgres;Password=19346jaidj"
  },
  "ClientSettings": {
    "ClientId": "13146fac-13e9-8d0c-aa4c-cfcf5246a153",
    "UseCache": true,
    "Mode": "Automatic"
  },
  "ConnectionSettings": {
    "NotifyUrl": "https://localhost:8080/hubs/NotificationHub/Send",
    "AlarmUrl": "https://localhost:8080/hubs/AlarmHub/Send"
  },
  "Kafka": {
    "Producer": {
      "BootstrapServers": "localhost:9092"
    },
    "Consumer": {
      "BootstrapServers": "localhost:9092"
    }
  }
}
